### ISSUE TITLE
Getting image in BGR format

### ISSUE THREAD

**Issue by kcimit** [laheller/SharpLibraw#1]
libraw_dcraw_make_mem_image produces image in bgr.
Is there is something in native (call or setting) library which can produce data in PixelFormat.Format24bppRgb?

The libraw class have method which can control this. But unfortunately it cannot be instanciated.

**Comment by jantheman** [comment]
Yeah, it is [copy_mem_image](https://www.libraw.org/docs/API-CXX.html#copy_mem_image) which is not available through the C API, only C++. You might want to try [LibRawWrapper](https://github.com/hurlbertvisionlab/librawwrapper) which wraps the C++ API.

**Comment by laheller** [comment]
@kcimit 

Are you sure? The libraw official doc says:

> libraw_processed_image_t ***dcraw_make_mem_image**(int *errorcode=NULL) - store unpacked and processed image into memory buffer as RGB-bitmap. This function allocates memory buffer and stores unpacked-preprocessed image into this buffer. Function returns allocated structure **libraw_processed_image_t** with filled fields. Always returns data as RGB bitmap (i.e. type field is equal to LIBRAW_IMAGE_BITMAP). dcraw_process() should be called before dcraw_make_mem_image();
> Returns NULL in case of an error. If caller has passed not-NULL value as errorcode parameter, than *errorcode will be set to error code according to error code convention.
> 

The C wrapper and this C# wrapper also has the **dcraw_make_mem_image** function. See the demo program for example use.

**Comment by jantheman** [comment]
I think the confusion is in the terminology. [This sample](https://docs.microsoft.com/en-us/dotnet/api/system.drawing.imaging.bitmapdata.scan0?view=net-5.0) suggests that `System.Drawing.Imaging.PixelFormat.Format24bppRgb` is actually BGR order in memory.

`dcraw_make_mem_image` [calls](https://github.com/LibRaw/LibRaw/blob/81ff865a95fefaa914103908a0e7257a27709660/src/postprocessing/mem_image.cpp#L283) `copy_mem_image` asking for RGB order. My guess is the issue is asking how to get the _other_ order.

**Comment by laheller** [comment]
Why it does matter? Once you have the image data in the memory (array, whatever), it's up to you, how or in what order you read and process it.

**Comment by jantheman** [comment]
I can't speak for the OP but it takes time and memory to convert between pixel formats. GDI+ bitmaps are served directly from the provided memory so if dcraw can already produce the correct format, it is considerable performance improvement.

**Comment by laheller** [comment]
Anyway, I see no issue here, as this code is nothing else then just a C# wrapper around libraw C-funtions and does exactly the same what we can expect from C-functions.
